/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { MockERC20__factory } from './MockERC20__factory.js';
export { StakingProtocol__factory } from './StakingProtocol__factory.js';