/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MockERC20 } from './MockERC20.js';
export type { StakingProtocol } from './StakingProtocol.js';
export * as factories from './factories/index.js';
export { MockERC20__factory } from './factories/MockERC20__factory.js';
export { StakingProtocol__factory } from './factories/StakingProtocol__factory.js';