/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface StakingProtocolInterface extends Interface {
    getFunction(nameOrSignature: "addRewards" | "claimRewards" | "getUserRewards" | "getUserStakedAmount" | "lastRewardTime" | "owner" | "periodFinish" | "rewardDuration" | "rewardRate" | "rewardToken" | "setRewardRate" | "stake" | "stakingToken" | "users" | "withdrawAll" | "withdrawAmount"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'addRewards', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'claimRewards', values?: undefined): string;
encodeFunctionData(functionFragment: 'getUserRewards', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getUserStakedAmount', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'lastRewardTime', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'periodFinish', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardDuration', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardRate', values?: undefined): string;
encodeFunctionData(functionFragment: 'rewardToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'setRewardRate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stakingToken', values?: undefined): string;
encodeFunctionData(functionFragment: 'users', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdrawAll', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdrawAmount', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'addRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserRewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getUserStakedAmount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lastRewardTime', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'periodFinish', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardDuration', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rewardToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRewardRate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stakingToken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'users', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawAll', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdrawAmount', data: BytesLike): Result;
  }

  

  export interface StakingProtocol extends BaseContract {
    
    connect(runner?: ContractRunner | null): StakingProtocol;
    waitForDeployment(): Promise<this>;

    interface: StakingProtocolInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    addRewards: TypedContractMethod<
      [rewardTokens: BigNumberish, duration: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    claimRewards: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getUserRewards: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getUserStakedAmount: TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    lastRewardTime: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    periodFinish: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rewardDuration: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rewardRate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    rewardToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setRewardRate: TypedContractMethod<
      [_rewardRate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stakingToken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    users: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint] & {stakedAmount: bigint, rewards: bigint, userRewardsPaid: bigint }],
      'view'
    >
    

    
    withdrawAll: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    withdrawAmount: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'addRewards'): TypedContractMethod<
      [rewardTokens: BigNumberish, duration: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimRewards'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getUserRewards'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getUserStakedAmount'): TypedContractMethod<
      [user: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lastRewardTime'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'periodFinish'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rewardDuration'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rewardRate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rewardToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setRewardRate'): TypedContractMethod<
      [_rewardRate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stakingToken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'users'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint] & {stakedAmount: bigint, rewards: bigint, userRewardsPaid: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'withdrawAll'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'withdrawAmount'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }